# Generated by Django 5.2.8 on 2025-12-01 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_note_category_note_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='note',
            name='share_token',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
