# Generated by Django 5.2.8 on 2026-04-09 21:02

import notes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=notes.models.note_upload_path),
        ),
    ]
